### ISSUE TITLE
Don't regenerate date footers for all yard docs on each small fix?

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#11]
This isn't really important, but if you look at the diff of each commit, every HTML file has a changed date, and this makes looking for the actual change really difficult in the git commit history. Easiest option is just remove date in the erb footer:

https://stackoverflow.com/questions/10959850/how-to-customize-diff-git-to-ignore-yard-date-generation

**Comment by htdebeer** [comment]
Okay. I've removed the generated API documentation from the repository. You can see it [here](https://heerdebeer.org/Software/markdown/paru/documentation/api-doc/) or build it manually by running `rake yard`. After today, you should see only changes in the code and user documentation in the git commit history.

**Comment by iandol** [comment]
Great, thanks!
