### ISSUE TITLE
Pry break Paru filters

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#14]
This is quite bizarre, but when I try to use the excellent [Pry](https://github.com/pry/pry) (0.10.4) to inspect a filter, I get a Paru error.

test.md
```markdown
A minimal **pandoc** example.
```

noop filter
```ruby
#!/usr/bin/env ruby
require 'pry'
require 'paru/filter'

binding.pry
Paru::Filter.run do 

end
```

Output:
```shell
👉  pandoc -t json -F noop test.md
/Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.8/lib/paru/filter/document.rb:61:in `rescue in from_JSON': Unable to read document. (Paru::FilterError)

Most likely cause: Paru expects a pandoc installation that has been
compiled with pandoc-types >= 1.17.0.5. You can
check which pandoc-types have been compiled with your pandoc installation by
running `pandoc -v`.

Original error message: 765: unexpected token at ''
	from /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.8/lib/paru/filter/document.rb:57:in `from_JSON'
	from /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.8/lib/paru/filter.rb:237:in `document'
	from /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.8/lib/paru/filter.rb:264:in `filter'
	from /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.8/lib/paru/filter.rb:228:in `run'
	from /Users/ian/.pandoc/filters/noop:8:in `<main>'
pandoc: Error running filter /Users/ian/.pandoc/filters/noop
Filter returned error status 1
```

What is strange is that pry should stop execution at the run() — if you comment out `binding.pry` then there is no error. I also tried the new `binding.irb` and that also has problems.

**Comment by htdebeer** [comment]
It seems pry is doing something with STDIN and/or STDOUT.

If I run the following filter

```
#!/usr/bin/env ruby

require "pry"
require "paru/filter"

input = $stdin.read
in_stream = StringIO.new(input)
out_stream = StringIO.new()

binding.pry
Paru::Filter.new(in_stream, out_stream).filter do 
end

output = out_stream.string

warn output
puts output
```

I do get the output on STDERR, but pandoc does not receive anything on STDIN. If I send pry's output to STDERR, I see it enters in debug mode, waiting for input.

I am not familiar with pry, so I cannot help you much further, unfortunately.

**Comment by iandol** [comment]
OK, no big issue, byebug still works so I'll just use that (I'm not a Ruby programmer, so these kinds of introspection tools help me understand what I'm doing!).

**Comment by iandol** [comment]
OK, the problem seems to indeed be that Pry uses Readline and stdin:

https://stackoverflow.com/questions/32333962/pry-not-stopping-when-called-from-a-ruby-script-that-reads-from-stdin

so this works:

```ruby
#!/usr/bin/env ruby
require 'pry'
pry_in = IO.new(IO.sysopen("/dev/tty", "r+"))
Pry.config.input = pry_in

require 'paru/filter'

binding.pry

Paru::Filter.run do
  x = metadata
end
```

Now it is possible to step into the filter and inspect the metadata, and test the new methods interactively...

**Comment by htdebeer** [comment]
Awesome work researching this issue. Thank you.
