### ISSUE TITLE
insert_code_block.rb can't modify first element of the document

### ISSUE THREAD

**Issue by xbelanch** [htdebeer/paru#16]
Working with insert_code_block.rb filter doesnt allow to modify the first of the block element of the document inserted. I attached a zip with a simple demo (add a silly text in capitals at the beginning of every paragraph). Check out the PDF to see the issue.

[issue_insert_code_block.zip](https://github.com/htdebeer/paru/files/1071117/issue_insert_code_block.zip)

**Comment by htdebeer** [comment]
As a workaround, you can use two filters: one to insert the other documents, and a second one to work on the paragraphs. 

Although I agree with you that this behavior is a bit unexpected, I am not sure it is a bug: the Para that has been _replaced_ by a new document, has already been processed. I suppose inserting the new nodes after the current one and then removing the current one could work, though. That makes the filter slightly more complex, but better behaving. I'll look into this and'll update the documentation accordingly.

Note. For version 0.2.5 I am changing paru's API for working with metadata: metadata will be a regular Ruby Hash and the `yaml` method will be removed (as will all other special methods to manipulate the metadata)

**Comment by htdebeer** [comment]
I've created a fix in version 0.2.5.g.
