### ISSUE TITLE
Request: filter that split document onto single HTML files

### ISSUE THREAD

**Issue by xbelanch** [htdebeer/paru#17]
Hi!
That's not an issue. I started to write my own filter based on this: https://github.com/jdittrich/SplitMarkdownFilter/blob/master/writeSplitPandocJSON.js The problem is that my ruby skills are very limited. At the moment I'm stuck to figure out how to capture on Paru with every markdown content between level one headers.

I do appreciate any help.

**Comment by htdebeer** [comment]
That is an interesting problem you pose. In paru's manual, there is a section on [numbering figures per section](https://heerdebeer.org/Software/markdown/paru/#numbering-figures-and-chapters), which introduces the idea different kinds of selectors. Among those is the "follows" selector (`+`). However, as any node can occur between two level one headers, that's not really helpful.

However, a different approach would be to collect the nodes in between level one nodes and create separate documents from them. The [AST manipulation methods](https://heerdebeer.org/Software/markdown/paru/documentation/api-doc/Paru/PandocFilter/ASTManipulation.html) might come in handy to solve this problem. 

I will have to think about how to do this, though, for it is a different use of pandoc filters than that I've been writing in paru. This is a fun problem! 

I'll come back to you with some answers later this week.

**Comment by htdebeer** [comment]
I got some time to hack a script together that seems to do what you're asking for. In the end it was not too difficult to create:

```
#!/usr/bin/env ruby
require "paru/filter"

def titleize(header)
    header.inner_markdown.gsub(" ", "_").strip
end

def new_document()
    Paru::PandocFilter::Document.new Paru::PandocFilter::CURRENT_PANDOC_VERSION, [], []
end

doc = new_document
chapters = {}

Paru::Filter.run do 
    with "Header" do |header|
        if header.level == 1
            doc = new_document
            chapters[titleize(header)] = doc
        end
    end
    doc << current_node if current_node.parent.is_a? Paru::PandocFilter::Document
end

chapters.each do |title, document|
    filename = "#{title}.md"

    Paru::PandocFilter::AST2MARKDOWN.configure do
        output filename
    end << document.to_JSON

end
```

It does the following:

1. Create a Hash with "title" => Document pairs, `chapters`, initially empty
2. For each Header node of level 1, create a new "title" => Document pair in the `chapters` Hash. Or, in other words, for each chapter create a new Document. 
3. Each node that is a direct child of the document that is being filtered, add it to the latest created chapter Document.

After the filter, these chapters are serialized to markdown files by using the chapter's title as the file name. The document is then converted to markdown using Paru with the pre-defined `AST2MARKDOWN` converter. You could use your own converter, of course, by creating a `Paru::Pandoc.new do ... end` object.

**Comment by xbelanch** [comment]
Thanks a lot! but... but I have a slighty problem around paru installed versions on my local machine. I uninstalled 0.2.4.8 paru gem I downloaded the new version and installed without any issue.

$ sudo gem install paru-0.2.4.9.gem 
Successfully installed paru-0.2.4.9
Parsing documentation for paru-0.2.4.9
Installing ri documentation for paru-0.2.4.9
Done installing documentation for paru after 0 seconds
1 gem installed

I verified everything is okay:

$ gem list --local

*** LOCAL GEMS ***

paru (0.2.4.9)

When I test your script it complains that doesnt find the constant AST2MARKDOWN:

././chapters2documents.rb:28:in `block in <main>': uninitialized constant Paru::PandocFilter::AST2MARKDOWN (NameError)
Did you mean?  Paru::PandocFilter::Markdown
	from ././chapters2documents.rb:25:in `each'
	from ././chapters2documents.rb:25:in `<main>'
pandoc: Error running filter ./chapters2documents.rb
Filter returned error status 1

I checked the node.rb lib/paru/filter/node.rb at local but... (more /var/lib/gems/2.3.0/gems/paru-0.2.4.9/lib/paru/filter/node.rb) but it seems that the code still belongs to the last version...

Sure it's my fault but I don't know how I could fix it...

Thanks in advance!

**Comment by htdebeer** [comment]
Could you try with version 0.2.5f? When I wrote that `chapters2documents.rb` script I was also working on the 0.2.5 release, so maybe I've used something that isn't in the 0.2.4.9 release.

**Comment by xbelanch** [comment]
My bad... and yep! it works! I followed the main documentation that points to 0.2.4.9 release (and I understood as the last release). Maybe it'll be hepful add a reference to https://github.com/htdebeer/paru/tree/master/releases 

Sorry for wasting your time!

**Comment by htdebeer** [comment]
Please, waste my time away, that is the only way to improve my software. The more comments, suggestions, and questions the better.

Besides, this is mostly my fault: I should not be developing the new version in the codebase of the old. The 0.2.5x branch is still beta software, though. However, I hope to release the official version soon.
