### ISSUE TITLE
META-Metadata from Pandocomatic?

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#18]
I'm writing a filter where I want to change my modification based on whether the pandoc output format is docx or latex. It would be good if pandocomatic could somehow pass this information to paru for use in filters. As far as I can tell you strip the pandocomatic_ field before invoking pandoc (I can't see it in metadata anyway). The easiest way to solve this is to keep pandocomatic_: and add the to: field from the pandocomatic.yaml template to the document metadata before pandoc gets it. That way a filter would have this info available to use.

**Comment by htdebeer** [comment]
It isn't pandocomatic that is stripping that metadata, but pandoc:

Run the following metadata through pandoc with `pandoc --from markdown --to json`:

```
---
pandocomatic_:
  some: value
...

hello
```

I get back:

```
{"blocks":[{"t":"Para","c":[{"t":"Str","c":"hello"}]}],"pandoc-api-version":[1,17,0,5],"meta":{}}
```

That means that we need to use some other way of communicating between pandocomatic and pandoc. The most easiest way being to use property `pandocomatic` again instead of `pandocomatic_`. (Or rename it temporarily)

**Comment by iandol** [comment]
Ah, OK. 

So the easiest thing is a way to pass an argument to a pandocomatic preprocessor I think which could then modify the metadata directly with a simple regex. As `$stdin` is where the document is passed we need to either prepend the `$stdin` content with a custom field, or somehow use another pipe to communicate. Another (simpler?) way is that pandocomatic creates a temporary file in the working directory with serialised yaml data, and a preprocessor (or I suppose even pandoc filter) can load that data and then use it? Then pandocomatic deletes the file before exiting.

The problem then becomes how we tell pandocomatic to do this — we could use a special preprocessor name but that is a bit hacky... Perhaps an explicit option to pandocomatic `filterData: true`

This is a actually an issue for pandocomatic not paru, should I close this and open an issue there or leave the discussion here?

**Comment by iandol** [comment]
Actually a command line option is probably easier right? 

ConvertFileCommand could parse the template for each subcommand and add `@to` to each subcommand Hash. Then ConvertFileMultipleCommand.execute for each subcommand could write this to the temp file for each invocation.

**Comment by iandol** [comment]
I've made a pull request using the FileInfoProcessor as a way to pass this info to paru (or any other) filters:

https://github.com/htdebeer/pandocomatic/pull/26

**Comment by htdebeer** [comment]
Yes, thanks. I've merged it and created a new version for pandocomatic and uploaded it to rubygems. I'll close this issue now.
