### ISSUE TITLE
Allow multiple versions of pandoc / prepare for pandoc 2

### ISSUE THREAD

**Issue by htdebeer** [htdebeer/paru#20]
Issue created in reaction to the [pandocomatic issue: Broken with Pandoc 2](https://github.com/htdebeer/pandocomatic/issues/28).

Currently [pandoc 2](https://github.com/pandoc-extras/pandoc-nightly) is in the making. This new major version promises some API changes. Although it might be a while before it is released, it is good to be prepared for when it is. Particularly because it is not unlikely that some users will keep on using the 1.x range while others start using the 2.x range.

I suggest adding an environment variable, `PARU_PANDOC_PATH`, that can be used to choose which version of pandoc to use. If no such environment variable exists, or if the path does not resolve, try to use the `pandoc` executable in the system's `PATH`. Paru's pandoc API will change with the pandoc version used: some pandoc CLI options in 1.x are not there in 2.x and vice versa.

**Comment by htdebeer** [comment]
Checked in a new version that supports multiple versions of pandoc. Note: some tests fail when running with pandoc2 due to differences in output generated by pandoc2 compared to pandoc1. These are ignored for now as pandoc2 is far from being released and its API/output can change still.

**Comment by iandol** [comment]
The weather wasn't that great then? 😄 Thanks Huub!

The AST is changing too, there will be some new elements (for example the RAW block/inlines). Shall I open an issue to keep track of these changes to the AST that Paru will need to support?

**Comment by htdebeer** [comment]
It's raining, again. As it will the whole next week, it looks like. Blergh :-(

Anyway, getting in front of the pandoc 2 changes is a good idea. We can tag these issues with label "pandoc2compatibility".
