### ISSUE TITLE
More of one argument

### ISSUE THREAD

**Issue by xbelanch** [htdebeer/paru#26]
Hi!

Guess it's not a bug :), simply my low ruby skills. How can I pass arguments from command line to a filter?

**Comment by htdebeer** [comment]
Actually, it is more of a pandoc issue :-)

You cannot pass arguments to a filter directly. However, you can pass information to a filter via:

- environment variables
- pandoc metadata

The latter solution would look something like:

```
pandoc --from markdown --to markdown -M myprefix="hi" --filter ./metadatafilter.rb testfile.md
```

with the `metadatafilter.rb`:

```
#!/usr/bin/env ruby
require "paru/filter"

Paru::Filter.run do 
        with "Para" do |p|
            p.inner_markdown = metadata['myprefix'] + ": " + p.inner_markdown
        end
end
```

It would prepend "hi" in front of each paragraph in `testfile.md`

It is probably a good idea to first check if `metadata['myprefic']` does exist, though. If you don't and it does not exist, the filter will crash. 

I hope this clarifies things a bit.
