### ISSUE TITLE
--toc-depth is missing in Pandoc 2 command line YAML

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#27]
```
👉  pandoc -h
pandoc [OPTIONS] [FILES]
...
                        --toc, --table-of-contents
                        --toc-depth=NUMBER
...
```

https://github.com/htdebeer/paru/blob/paru-for-pandoc2/lib/paru/pandoc_options_version_2.yaml

I'm not sure what the default value is...

**Comment by htdebeer** [comment]
According to the [manual](http://pandoc.org/MANUAL.html) the default value is 3. The odd thing is, it is already in version 1 of the options list.

I've created a fix for it.
