### ISSUE TITLE
documentation: using filters with pandoc

### ISSUE THREAD

**Issue by rriemann** [htdebeer/paru#3]
Hello,

I just discovered this neat project and will look into it more closer in the future. I already have one question: Is it possible to use the paru filters within the original pandoc command, e.g. `pandoc --filter=my-paru-filter.rb`?

**Comment by htdebeer** [comment]
Dear Robert,

On woensdag 15 maart 2017 06:37:23 CET Robert Riemann wrote:
> I just discovered this neat project and will look into it more closer in the
> future. I already have one question: Is it possible to use the paru filters
> within the original pandoc command, e.g. `pandoc
> --filter=my-paru-filter.rb`?

Yes you can! As long as "my-paru-filter.rb" is an executable file and in your PATH 
somewhere, you're golden.

For some extra examples to play with, see also: https://github.com/htdebeer/paru-filter-collection.

If you do have any questions, do not hesitate to ask,

with kind regards,
-- 
Huub de Beer
