### ISSUE TITLE
After fixing running paru on windows, tests with paths with spaces fail on windows

### ISSUE THREAD

**Issue by htdebeer** [htdebeer/paru#31]
After fixing running paru on windows, tests with paths with spaces fail on windows. Just run `rake test` on Windows.

**Comment by agusmba** [comment]
probably a shot in the dark, but [elsewere](https://github.com/browserify-rails/browserify-rails/pull/89) problems with spaces in ruby/windows were solved using `Shellwords.shellescape`

**Comment by htdebeer** [comment]
That's the odd thing, I already use `shellescape`. But maybe I am using it to early or to late when creating a pandoc command. I'll look into this. Thanks for the tip!

**Comment by htdebeer** [comment]
This might also be related to the fact that pandocomatic cannot find its default data directory on windows.

**Comment by agusmba** [comment]
Yes, I saw that.
In order to continue testing pandocomatic, I created it manually to get past that error.
You can see where it's supposed to be using `pandoc -v`

**Comment by htdebeer** [comment]
Yes. But paru runs `pandoc -v` to determine pandoc's data directory. Somehow, using these paths doesn't work on Windows. I'll look into that next week.

**Comment by htdebeer** [comment]
Just checked in a fix for escaping paths on Windows; all tests are now green.
