### ISSUE TITLE
Allowing the use of stop! at start of filter

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#32]
As we discussed by email, if I use a conditional to test a metadata key exists at the start of a filter, stop! does not actually stop, but carries on.

```ruby
Paru::Filter.run do
  stop! unless metadata.key?('institute')
  #do something with metadata key, this gets called even if 'institute' key never existed
end
```

The simple fix is to just wrap the rest of the filter in an `if` statement, but it seem to be ruby "style" to return early in this fashion...

**Comment by htdebeer** [comment]
I made `stop!` stop immediately. This change seems to work, but I am unable to test it automatically via `rake test` because exiting in a script seems also to stop the automated tests. Nevertheless, the change is small so I believe it is okay.

It is in version 0.2.5.12
