### ISSUE TITLE
Filter applied for a specific output format

### ISSUE THREAD

**Issue by xbelanch** [htdebeer/paru#33]
Is it possible to choose an specific output format on the context of a filter? Let me explain: for a some reason, I want to change the uri of the wholes images of a document but only for the HTML ouput, not for PDF output (and mantaining the original images uri on that last case)

**Comment by iandol** [comment]
The way I do it is to test for `"pandocomatic-fileinfo"` metadata which will contain the `"to"` key which you can match with a regex, example below only runs filter if document has `to=docx`

```ruby
require 'paru/filter'

Paru::Filter.run do
  if metadata.key?('pandocomatic-fileinfo') && metadata[pKey]['to'].match(/docx/)
    #rest of filter
  end
  stop!
end
```

**Comment by htdebeer** [comment]
Interesting question. As far as I know, pandoc does not mix-in its state or even the command-line options  it was invoked with into an accessible form. The only API a filter has access to is the document, pandoc's version, and the metadata (contained in the document). Neither of which does contain the output format or any other command-line option (except `--metadata` of course).

I suppose it is the reverse problem from the requests of having a way to specify pandoc's command-line options in a document's metadata. Just like that problem, this one can be solved by a wrapper script that reads the command line options and then mixes them in into the document's metadata.

We can do that in pandocomatic, or even in paru (in Paru::Pandoc, that is), but that will not work when a filter is called via pandoc directly.

**Comment by xbelanch** [comment]
Maybe I'm wrong but after reading the documentation of this project (https://github.com/bk/pdc) I think it could be a possible workaround: using pandocomatic with 'filter-format-<format>' option in the YAML meta block instead of change or modify the core of Paru.

**Comment by htdebeer** [comment]
True. When calling pandoc from pandocomatic we have enough information about the conversion process to mix in this kind of information. Would you like me to mix in the output format in the `pandocomatic-fileinfo` metadata property that pandocomatic automatically adds to each file it converts?

**Comment by bmc** [comment]
The Python [panflute](http://scorreia.com/software/panflute/code.html) filter library presents the output format to a custom filter, as a field on its version of the `document` object. I have successfully used `panflute` to inject output format-specific raw blocks into Pandoc-generated LaTeX, HTML and ePub files.

When invoked as follows:

```
pandoc -t FMT -F ./my-filter my_input.md
```

`pandoc` will pass the argument to `-t` as the first command line parameter to the filter. `panflute` uses that argument, defaulting to "html" if it's not present.

With `paru`, you can obviously just query `ARGV[0]`, provided you're invoking the filter as shown above.

**Comment by htdebeer** [comment]
Thanks for the observation! I tried it here successfully as well: you are correct, pandoc passes the output format as the only argument to a filter.

**Comment by htdebeer** [comment]
To give an example with Ruby and paru, albeit a useless one:

```{.ruby}
#!/usr/bin/env ruby
require "paru/filter"

format = if ARGV.first.nil? then "unknown" else ARGV.first end

Paru::Filter.run do
    with "Strong" do |strong|
        if "markdown" == format then
            strong.markdown = "*#{strong.inner_markdown.strip}*"
        else
            strong.markdown = "~#{strong.inner_markdown.strip}~"
        end
    end
end
```

This filter will transform `**text**` to `*text*` when converting to markdown and transform it to `~text~` otherwise.

**Comment by xbelanch** [comment]
Amazing! I'll try to write a simple  filter where it converts a youtuble url into a "iframe" (in case of HTML output) and other bunch of code (https://tex.stackexchange.com/questions/393693/how-to-embed-a-youtube-video-or-other-streaming-in-html5-format) for PDF ouput and share if you think it could be an useful example (hope I'll not need to bother you!).

**Comment by htdebeer** [comment]
I am looking forward to your example. Feel free to bother away!

**Comment by iandol** [comment]
I'm confused why the suggestion of using 

```ruby
if metadata['pandocomatic-fileinfo']['to'].match(/FORMAT/)
```

did not work (it did work for me)...

**Comment by htdebeer** [comment]
If you call the filters via pandocomatic, you're right. However, paru can also be used to write filters you call directly via pandoc and then there won't be no "pandocomatic-fileinfo" metadata mixed in. 

Luckily, as bmc observed, pandoc already passes the output format as an argument to a filter, so it is supported by default regardless of using paru or pandocomatic.

**Comment by xbelanch** [comment]
I wrote a boilerplate but functional filter example that detects a command inside markdown document (::insert::media::<youtube url>) and generate an embed tag in case of html output format and a simple qr code in case of pdf output format =) Do feel free to improve it!

https://gist.github.com/xbelanch/0c25fa87abe9d03a34c6cf9e4f4d2066

**Comment by iandol** [comment]
@htdebeer ah yes, that makes sense!!! :-)
