### ISSUE TITLE
undefined method `epub_stylesheet'

### ISSUE THREAD

**Issue by chinhodado** [htdebeer/paru#36]
I'm having this issue with paru:

    C:/abc/methods.rb:44:in `block in gen_epub': undefined method
     `epub_stylesheet' for #<Paru::Pandoc:0x0000000002a08be0> (NoMethodError)
    Did you mean?  epub_chapter_level
            from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/paru-0.3.0.0/lib/paru/pandoc.rb:137:in `instance_eval'
            from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/paru-0.3.0.0/lib/paru/pandoc.rb:137:in `configure'
            from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/paru-0.3.0.0/lib/paru/pandoc.rb:107:in `initialize'

What is going on here?

**Comment by chinhodado** [comment]
I believe I found the cause. From the pandoc 2.0 release note:

> Removed --epub-stylesheet; use --css instead (#3472, #847). Multiple stylesheets may be used. Stylesheets will be taken both from --css and from the stylesheet metadata field (which can contain either a file path or a list of them).

**Comment by htdebeer** [comment]
That is correct. The error message you added tells us that paru did not create the `epub_stylesheet` method. Because the `--epub-stylesheet` is no longer part of pandoc 2, it has not been listed to be created in paru.

**Comment by htdebeer** [comment]
Just to be complete, if you run paru with pandoc1, that option / method is still available.
