### ISSUE TITLE
Feature Request: with_startup

### ISSUE THREAD

**Issue by rriemann** [htdebeer/paru#38]
Hello,

you provide the following example code:

```ruby
Paru::Filter.run do 
    metadata.delete "pandoc"
end
```

I added a print statement and noted that this line is actually called many times. It would be nice if it could be executed only once and if one can control if it is executed before other `with "selector"` blocks or after.

**Comment by htdebeer** [comment]
I do know of this issue. See also https://github.com/htdebeer/paru/issues/15.

The problem is with how paru is setup internally. I fear there is no quick fix, but it is something to think about when developing a next version of paru. I'll put it on the roadmap. Ideas and suggestions welcome.

**Comment by htdebeer** [comment]
I have been thinking about this issue for a bit. I think that running a piece of code for each and every element in a document's AST by default is not desired behavior. Of course, changing this affects every filter that relies on this behavior. On the other hand, I think it would be better to explicitly ask for this behavior. For example, using a "*" selector that means "each and every element in the AST". 

Furthermore, I could add a "Document" selector that is run once at the start of the filtering process, and is ignored after that. Or maybe a "Document start" and "Document end" selector would even be nicer as it gives more fine grained control about when to run a document-related filter. This could even allow you to switch on some metadata in the "Document start" filter and clean up again in the "Document end" filter.

I think I can add these new selectors without too much trouble. The questions is: Should I disable the existing behavior of "empty" selectors? I can keep it, but advertise the new way of doing things in the manual and examples. That would mean that the new way of working is backwards compatible with the previous way of working.

**Comment by htdebeer** [comment]
This feature will be available in the next release of paru.
