### ISSUE TITLE
documentation: add minimum ruby version

### ISSUE THREAD

**Issue by rriemann** [htdebeer/paru#39]
Hello,

I experienced problems with paru because some packaged ruby version is too old and does not support require_relative. I think the minimum ruby version can be specified in the gemspec file.

According to https://www.rubydoc.info/gems/require_relative/1.0.3 , require_relative needs 1.9.2 or later.

The gem require_relative provides a backport

**Comment by htdebeer** [comment]
Thanks for your comment.

I do not know what Ruby version is needed, but I've [added](https://github.com/htdebeer/paru/commit/d3d085cadbd1bc48b0adbd4d19f2c4713b67f4db) the oldest release [still getting security updates](https://www.ruby-lang.org/en/downloads/branches/), which is currently [2.3.7](https://www.ruby-lang.org/en/downloads/releases/). I'll try to keep this gemspec property updated.

Unless you need this patched, I'd prefer not to create a new Paru version for this. It'll be in the next version that is created after a bug fix / feature addition. (Although I do not know when that will be for there are no current bugs or feature requests.)
