### ISSUE TITLE
Manipulating metadata in a filter is cumbersome / impossible

### ISSUE THREAD

**Issue by htdebeer** [htdebeer/paru#4]
It is not always possible to add or change the metadata in a filter. For example, I can delete a key-value from a MetaMap, but I cannot add one. Adding a simple string involves creating a MetaString, which is more complex than just setting a string. And I am not sure how to set MetaInline or MetaBlock easily, if at all.

**Comment by htdebeer** [comment]
I have added the following methods to manipulate metadata:

- has?(selector)
- set(selector, value)
- replace(selector, value)
- get(selector, value)
- delete(selector)

and a utility module Metadata to convert a well-formed YAML string to a pandoc MetaMap

**Comment by iandol** [comment]
OK, great thank you! I will have a play with trying to rewrite metadata based on this Pandoc issue when I get time: 

https://github.com/jgm/pandoc/issues/3696

Basically for academic use, metadata for author breaks Word output if you use a hash logical structure for name and affiliation. So one needs to rewrite a sequence of hashes into a sequence, but only for Word output.

**Comment by htdebeer** [comment]
All right. Do note that the new metadata functionality is available in version 0.2.5d, not per sé in 0.2.4.x.

**Comment by iandol** [comment]
This is still quite cumbersome. The MetaMap is not easily designed for iterating through setting values. So lets say I have:

```yaml
authorbad:
  - John Doe
authorgood:
  - name: John Doe
```

and I want the `authorbad` child sequence "John Doe" to become similar to the `authorgood` map: "name: John Doe". 

If we could use a Ruby style array/hash array API this would be trivial (pseudocode):

```ruby
a = metadata.get_native('authorbad')
i = 1
a.children.each do | c |
  if not c.is_a?(Hash)
    name = c[0]
    a.children[i] = {'name': name}
  end
end
metadata.set_native('authorbad',a)
```

The idea is to "convert" metadata to an Ruby array/hash structure, and then we can easily iterate and restructure. At the moment get() and set() only work on a MetaMap, so if you have to iterate through children you have to keep track and setting the data is not trivial (i.e. I can't use get/set() on fields within metadata).

As I say, I'm not a Ruby programmer so perhaps I've missed something major here.

**Comment by htdebeer** [comment]
No, you are correct. The issue is with pandoc: most strings in the YAML metadata are converted to Inline and Block elements, not simple string values. To overcome this issue I propose to also add a MetaMap to YAML converter method (with caching) that uses pandoc to convert a MetaMap to YAML and a MetaMap to Hash converter method that uses the MetaMap to YAML to generate a Hash. This Hash then contains plain strings/numbers/booleans you can easily manipulate. It can also be converted to YAML again, which can be set as metadata.

**Comment by iandol** [comment]
Yes, this makes sense, YAML⬄RubyHash serialisation as the frontend to manage metadata will be much more user-productive. Paru can already convert MetaMap⬄YAML, and I think that the MetaMap should be more of a backend format as it isn't so easy to work with, so the API should expose the RubyHash and YAML input as the "preferred" methods to edit metadata. I think this certainly makes Paru more friendly than Panflute's API, where you can get a python structure but I don't see it being easily two-way:

http://scorreia.com/software/panflute/code.html#panflute.elements.Doc

**Comment by htdebeer** [comment]
I've added a way to set/replace metadata via both YAML Strings and Ruby Hashes. The `get` method still returns a pandoc metadata node, but if it is a MetaMap (or Meta), you can convert it to YAML and a Hash using the methods `to_yaml` and `to_hash`.

It is still not optimal: for each time you want to update/inspect the metadata as a Hash, pandoc is run. Although these conversions are cached, each change will mean a new conversion still.

The easiest way to overcome this problem is to offer only a Hash API to the metadata in a filter. On the other hand, this makes it harder to access pandoc nodes in values in the metadata. But I do not think that's something many people want to use anyway.

**Comment by iandol** [comment]
I get this error:

```
 => 13:     mh = metadata.to_hash;

[1] pry(#<Paru::Filter>)> next
/Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paru-0.2.5e/lib/paru/metadata.rb:59:in `to_yaml': undefined method `to_ast' for nil:NilClass (NoMethodError)
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paru-0.2.5e/lib/paru/metadata.rb:86:in `to_hash'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paru-0.2.5e/lib/paru/filter/meta_map.rb:222:in `to_hash'
	from /Users/ian/.pandoc/filters/noop2:13:in `block in <main>'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paru-0.2.5e/lib/paru/filter.rb:267:in `instance_eval'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paru-0.2.5e/lib/paru/filter.rb:267:in `block in filter'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paru-0.2.5e/lib/paru/filter/ast_manipulation.rb:100:in `each_depth_first'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paru-0.2.5e/lib/paru/filter.rb:265:in `filter'
	from /Users/ian/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/paru-0.2.5e/lib/paru/filter.rb:228:in `run'
	from /Users/ian/.pandoc/filters/noop2:9:in `<main>'
```

**Comment by htdebeer** [comment]
Meanwhile, I've removed the `to_yaml` and `to_hash` convenience methods. In version 0.2.5f the metadata in a filter is always a hash. You can manipulate it as much as you like and after the filter has been run, it'll be converted back to pandoc metadata again.

I am thinking about moving the `set`, `get`, `has?` methods from MetaMap to Filter somehow. On MetaMap they aren't used anymore because access to the metadata goes via a Hash, but inspecting and manipulating a complex Hash structure is quite cumbersome in Ruby.

**Comment by iandol** [comment]
do you mean that the new `has?` `set` `get` etc. would work on any descendant key, without needing to walk through the children?

**Comment by htdebeer** [comment]
Yes. Yesterday I've added `set_by`, `get_by`, `has_by?`, and `delete_by`, that takes as argument a selector (dot separated property keys) and in case of the `set_by` a new value to set. Having slept on it, I am not sure I like it very much:

- There are multiple gems to work with nested Hashes, so I'd suppose a user can use one of those if she's so inclined. 
- In Ruby 2.3, I believe, the Hash (and Array) have gotten the `dig(keys...)` method to dig into a nested container structure. This means that the `get_by` and `has_by?` are already implemented in the core Hash class anyway.
- How often do you think users work with (sparse) nested metadata structures anyway? 
- I am not sure what the behavior for `set_by` should be exactly. Should there also be a `replace_by` method which replaces a property, while `set_by` mixes in the new value with the old? What about non-existing properties? Should they be added or should the `set_by` fail because of them?

**Comment by iandol** [comment]
I think I agree that this added complexity does not contribute to most metadata manipulation tasks I can think of, and as you say, a user can simply use a gem/modern ruby version to handle this (this is the benefit of using a Hash+Array for the metadata), so I'd vote to simplify the API!

**Comment by htdebeer** [comment]
All right, I'll remove it again next Wednesday and I'll add some examples of filters with nested metadata to the manual and/or API documentation.
