### ISSUE TITLE
image.attr.has_keys? fails as it expects a map but gets an Array

### ISSUE THREAD

**Issue by hegger** [htdebeer/paru#41]
The following code snippet fails in line
> if image.attr.has_key? "width" with error
gems/paru-0.3.0.1/lib/paru/filter/attr.rb:72:in `has_key?': undefined method `key_exists?' for #<Array:0x00005604c3b8bc80>

`require "paru/filter"

Paru::Filter.run do 
  with "Image" do |image|
    if image.attr.has_key? "width"
      STDERR.puts  "has width"
    end
  end
end
`

**Comment by htdebeer** [comment]
I can reproduce the issue. Apparently, the attributes are a list of key-value pairs which have not been converted to a Hash by paru. I will fix this.

**Comment by htdebeer** [comment]
I released paru version 0.3.1.0 with a fix for this issue. Please upgrade to this version and try your example again. Feedback is welcome.

**Comment by hegger** [comment]
Immediate reaction. I'm impressed.
The bug fix works nicely. 
Thank you very much.
