### ISSUE TITLE
howto: capturing a bunch of paragraphs

### ISSUE THREAD

**Issue by xbelanch** [htdebeer/paru#42]
Hi after a long time!
I'm struck trying to capture this block of paragraphs to generate a custom html output. For example. I want to capture all the markdown code inside :::alert and :::

```
:::alert
A simple **alert**

with a few paragraphs and...

other stuff like lists:

* One
* Two
:::
```

and produce some custom HTML output like this:

```
<div class="alert">
<p>A simple <strong>alert</strong></p>

<p>with a few paragraphs and...</p>

<p>other stuff like lists:</p>

<ul><li>One</li><li>Two</li></ul>
</div>

```
Is that possible with Paru? 

Thanks in advance!

**Comment by htdebeer** [comment]
Good to hear from you again!

And yes, *of course* it is possible with paru :-) It is actually quite straightforward: Recognize a `Div` with class "alert" and replace that node by a `RawBlock` node with as contents the type "html" and the `Div` node's contents converted to HTML:

```ruby
#!/usr/bin/env ruby
require "paru"
require "paru/filter"

MD2HTML = Paru::Pandoc.new do
    from "markdown"
    to "html"
end

Paru::Filter.run do
	with "Div" do |div|
            if div.attr.classes.include? "alert"
                # Found an "alert" Div block: replace it by a HTML RawBlock with
                # the Div's contents converted to HTML
                div.parent.replace(div, Paru::PandocFilter::RawBlock.new(["html", MD2HTML << div.inner_markdown]))
            end
	end
end
```

While writing this solution I did discover that the `Div` node's `attr` property was not accessible. I fixed that in the latest release of paru: 0.3.1.1. Be sure to upgrade to that release when you try out this solution yourself. 

This solution does not surround the original `Div` node's content with an HTML div element, but that should not be too hard to do.

**Comment by xbelanch** [comment]
Oh Thank you so much! It works!

But still I'm wondering why three colons are translated to a "div" html block? (after google it for a while) Oh I see: https://pandoc.org/MANUAL.html#divs-and-spans

**Comment by htdebeer** [comment]
Your welcome; Have a nice end-of-year!
