### ISSUE TITLE
Accessing element.inner_markdown truncates at first space, occasionally

### ISSUE THREAD

**Issue by NickBarreto** [htdebeer/paru#43]
Hello! 

I wrote to you a few years ago asking about using EPUB as an input method for paru, and I've been using it ever since you implemented the convert_file method.

Inspired by the code in this related issue https://github.com/htdebeer/paru/issues/9, I'm using a paru filter to fine-tune the latex output of a document and it's proving really successful. 

This is the relevant snipped from my filter:

```
  # Change the output so chapters and sections aren't numbered
  with 'Header' do |header|
    header.inner_markdown = header.children.first.inner_markdown if header.has_children?
    if header.level == 1
      header.markdown = "\\chapter\*\{\\texorpdfstring\{\{#{header.inner_markdown}\}\}\{#{header.inner_markdown}\}\}"
    end
    if header.level == 2
      header.markdown = "\\section\*\{\\texorpdfstring\{\{#{header.inner_markdown}\}\}\{#{header.inner_markdown}\}\}"
    end
  end
```

In general, this works absolutely fine. However, in some instances, the result output includes only the first word in that header, rather than the full header text. 

For example, in the result file I would see something like this

```
\section*{\texorpdfstring{{London, 
}}{London, 
}}

or 

\section*{\texorpdfstring{{The 
}}{The
}}
```

when the expected output would have been

```
\section*{\texorpdfstring{{London, February 1907
}}{London, February 1907
}}

and

\section*{\texorpdfstring{{The Orient Express, August 1905
}}{The Orient Express, August 1905
}}
```

I can't seem to find any commonality in the instances where this occurs, but when there is a comma, that bit of punctuation is always preserved, and otherwise the string gets truncated at the first space. 

Am I accessing the wrong method with `.inner_markdown`? 

I've been looking at the input carefully and it's not that there is a child node in there I don't think – the source HTML from the EPUB input in this instance was `<h2>The Orient Express, August 1905</h2>`, for example.

This issue doesn't occur in every instance of a heading, but when it does occur in a specific heading it will happen every time I run paru, but as I said I can't quite ascertain what is causing it.

Do you have any ideas? Am happy to provide more examples and information to help debug this issue.

Thanks!

**Comment by htdebeer** [comment]
I can reproduce the issue when I run

```bash
echo "<h2>The Orient Express, August 1905</h2>" | pandoc --from html --to latex --filter ./unnumber_header.rb
```

With `unnumber_header.rb` containing a filter as presented by you above.

At a first glance, using the first child of the header seems to be the most likely culprit. I changed the filter to:

```ruby
#!/usr/bin/env ruby
require "paru/filter"

Paru::Filter.run do
    # Change the output so chapters and sections aren't numbered
    with 'Header' do |header|
        warn "header.children: #{header.has_children?} -> '#{header.children.map {|c| c.markdown}.join(";")}'"
        warn "header.level: #{header.level}"
        warn "header.inner_markdown 1: '#{header.inner_markdown}'"
        header.inner_markdown = header.children.first.inner_markdown if header.has_children?
        warn "header.inner_markdown 2: '#{header.inner_markdown}'"
        warn "header.markdown 1: '#{header.markdown}'"
        if header.level == 1
            header.markdown = "\\chapter\*\{\\texorpdfstring\{\{#{header.inner_markdown}\}\}\{#{header.inner_markdown}\}\}"
        end
        if header.level == 2
            header.markdown = "\\section\*\{\\texorpdfstring\{\{#{header.inner_markdown}\}\}\{#{header.inner_markdown}\}\}"
        end
        warn "header.markdown 1: '#{header.markdown}'"
    end
end
```

and run the above pandoc command again, resulting in the following output:

```
header.children: true -> 'The
;
;Orient
;
;Express,
;
;August
;
;1905
'
header.level: 2
header.inner_markdown 1: 'The Orient Express, August 1905
'
header.inner_markdown 2: 'The
'
header.markdown 1: 'The {#the-orient-express-august-1905}
---
'
header.markdown 1: 'The {#the-orient-express-august-1905}
---
'
```

This seems to suggest that updating the `inner_markdown` property with the first child's `inner_markdown` is not correct.

Why are you changing the header's `inner_markdown` property at all (in this way)? Because in this particular example, if I don't change it at all, the output seems to be fine.

**Comment by NickBarreto** [comment]
Ok, so the AST doesn't hold the full string of a heading as a single node. That certainly would explain why I can access it in this way. 

I'm not wanting to change`inner_markdown`, but rather just want to access it so the header text is included in the output. I'm doing it in this way because the tex command /texorpdfstring wants the string twice, so that any tex markup within the string can be removed in the second instance, as it would otherwise not be interpreted and would appear in the resulting PDF's internal bookmarks.

That said, I don't think this is that common an occurrence in out documents. 

Would there be a way to change the `heading.markdown` like this without passing the contents of it's respective `inner_markdown` in this way?

An output of simply `\section*{The Orient Express, August 1905}` would probably work just as well for me, but wouldn't `\\section\*\{#{header.inner_markdown}\}` suffer from the same issue?

**Comment by htdebeer** [comment]
As long as you don't set the `markdown` or `inner_markdown` properties in between the two times you use the `inner_markdown` property, the following should work:

```ruby
#!/usr/bin/env ruby
require "paru/filter"

Paru::Filter.run do
    # Change the output so chapters and sections aren't numbered
    with 'Header' do |header|
        if header.level == 1
            header.markdown = "\\chapter\*\{\\texorpdfstring\{\{#{header.inner_markdown}\}\}\{#{header.inner_markdown}\}\}"
        end
        if header.level == 2
            header.markdown = "\\section\*\{\\texorpdfstring\{\{#{header.inner_markdown}\}\}\{#{header.inner_markdown}\}\}"
        end
    end
end
```

And, of course, you can also store the `inner_markdown` property in a local variable and use that later on as many times as you like. For example:

```ruby
#!/usr/bin/env ruby
require "paru/filter"

Paru::Filter.run do
    # Change the output so chapters and sections aren't numbered
    with 'Header' do |header|
        header_text = header.inner_markdown

        if header.level == 1
            header.markdown = "\\chapter\*\{\\texorpdfstring\{\{#{header_text}\}\}\{#{header_text}\}\}"
        end
        if header.level == 2
            header.markdown = "\\section\*\{\\texorpdfstring\{\{#{header_text}\}\}\{#{header_text}\}\}"
        end
    end
end
```

**Comment by htdebeer** [comment]
As a final tip, you might want to strip the whitespace from the end of the `inner_markdown` property when you're using that later on, as it looks like a newline is added by paru (or pandoc). This will result in a nicer output. The script would then look like:

```ruby
#!/usr/bin/env ruby
require "paru/filter"

Paru::Filter.run do
    # Change the output so chapters and sections aren't numbered
    with 'Header' do |header|
        header_text = header.inner_markdown.strip

        if header.level == 1
            header.markdown = "\\chapter\*\{\\texorpdfstring\{\{#{header_text}\}\}\{#{header_text}\}\}"
        end
        if header.level == 2
            header.markdown = "\\section\*\{\\texorpdfstring\{\{#{header_text}\}\}\{#{header_text}\}\}"
        end
    end
end
```

**Comment by NickBarreto** [comment]
Yes, this make sense, thanks very much.

Doing some testing and the reason I was doing this assignment `header.inner_markdown = header.children.first.inner_markdown if header.has_children?` is that sometimes my headers had an inner span which I was aiming to strip out, and while that code worked to cleanup/prevent output like this,

```
\chapter*{\texorpdfstring{{[Chapter One]{.h2-inner}
}}{[Chapter One]{.h2-inner}
}}
```

it clearly introduced the bug in this issue. When that span is present, that correctly grabs the whole string of the heading because it's all held in the node of the span, but sometimes it was stepping down a level too far which is why I ended up with just the first word rather than the whole string! 

Can I test the child of the header node it's type of inline node?

Something along these lines of somewhat madeup code?

```
header_text = header.inner_markdown.strip
    if header.children.first.type "Span"
      header_text = header.children.first.inner_markdown
    end
```

I've been taking a look through the documentation and examples but haven't seen this sort of selector used.

**Comment by htdebeer** [comment]
Yes, you can inspect a node's type. Each node does have a [`type` method](https://heerdebeer.org/Software/markdown/paru/documentation/api-doc/Paru/PandocFilter/Node.html#type-instance_method), which returns that node's type as a string. You can change the filter to:

```ruby
#!/usr/bin/env ruby
require "paru/filter"

Paru::Filter.run do
    # Change the output so chapters and sections aren't numbered
    with 'Header' do |header|
        header_text = if not header.children.empty? and "Span" == header.children.first.type then
                          header.children.first.inner_markdown.strip
                      else
                          header.inner_markdown.strip
                      end

        if header.level == 1
            header.markdown = "\\chapter\*\{\\texorpdfstring\{\{#{header_text}\}\}\{#{header_text}\}\}"
        end
        if header.level == 2
            header.markdown = "\\section\*\{\\texorpdfstring\{\{#{header_text}\}\}\{#{header_text}\}\}"
        end
    end
end
```

Note that I do also check if the header has any children at all because otherwise if it doesn't have any children the code `header.children.first` probably crashes the program.

**Comment by htdebeer** [comment]
Actually, I just tested it with 

```bash
echo "<h2><span>The Orient Express</span>, August 1905</h2>" | pandoc --from html --to latex --filter ./unnumber_header.rb
```

and there's still a possibility for a crash with an empty header because of the `strip` method. A more robust solution is:

```ruby
#!/usr/bin/env ruby
require "paru/filter"

Paru::Filter.run do
    # Change the output so chapters and sections aren't numbered
    with 'Header' do |header|
        header_text = if not header.children.empty? then
                          if "Span" == header.children.first.type then
                              header.children.first.inner_markdown.strip
                          else
                              header.inner_markdown.strip
                          end
                      else
                          ""
                      end

        if header.level == 1
            header.markdown = "\\chapter\*\{\\texorpdfstring\{\{#{header_text}\}\}\{#{header_text}\}\}"
        end
        if header.level == 2
            header.markdown = "\\section\*\{\\texorpdfstring\{\{#{header_text}\}\}\{#{header_text}\}\}"
        end
    end
end
```

**Comment by NickBarreto** [comment]
This is doing the trick, yes. Amazing. Thank you so much Huub!
