### ISSUE TITLE
Add today's date filter not working

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#5]
Hi, I tried using the new example filter, which I renamed addToday in my local install and I get the following noMethod error:

```
/Users/ian/.pandoc/filters/addToday:8:in `block in <main>': undefined method `[]=' for #<Paru::PandocFilter::Meta:0x007fb7d612bc00> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.3/lib/paru/filter.rb:132:in `instance_eval'
	from /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.3/lib/paru/filter.rb:132:in `block in filter'
	from /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.3/lib/paru/filter/ast_manipulation.rb:92:in `each_depth_first'
	from /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.3/lib/paru/filter.rb:130:in `filter'
	from /Library/Ruby/Gems/2.0.0/gems/paru-0.2.4.3/lib/paru/filter.rb:108:in `run'
	from /Users/ian/.pandoc/filters/addToday:7:in `<main>'
pandoc: Error running filter /Users/ian/.pandoc/filters/addToday
Filter returned error status 1
```

----
filter:
```ruby
#!/usr/bin/env ruby
## Add today's date to the metadata

require "paru/filter"
require "date"

Paru::Filter.run do 
	metadata["date"] = Paru::PandocFilter::MetaString.new(Date.today.to_s)
end
```

**Comment by htdebeer** [comment]
I've created and uploaded a new version of Paru: 0.2.4.4. I forgot to do so last night. 

The metadata filter capabilities need some work. I plan that for version 0.2.5. The idea is to have a simple API to manipulate the metadata without needing to go about creating Meta* objects.

By the way, I also updated the API documentation for Filter: https://heerdebeer.org/Software/markdown/paru/documentation/api-doc/Paru/Filter.html

**Comment by iandol** [comment]
Yes I don't really understand how to deal with the Meta* objects, so a simpler API for metadata sounds brilliant!!!  Thank Huub!

**Comment by iandol** [comment]
Oh, and the API docs are very nice!

**Comment by htdebeer** [comment]
I started working on an improved metadata handling (see [MetaMap](https://heerdebeer.org/Software/markdown/paru/documentation/api-doc/Paru/PandocFilter/MetaMap.html))) and added the following methods to MetaMap (which is also used as the main metadata object):

- replace(selector, value)
- has?(selector)
- get(selector)
- delete(selector)

These methods take a selector, which is a string representation of a sequence of property names separated by a period ("."). For example, "pandoc.from" would select the "from" property in the "pandoc" property.

Furthermore, I've added a "yaml" method, which takes a YAML string, converts it to a MetaMap and is mixed into the current metadata object.

What do you think of this API? What methods am I missing still? And can you give some examples of metadata manipulation you would like to perform in your filters?

(I am mostly setting simple properties like dates, keywords, and pandoc options, but I suppose other people can have quite complex metadata structures)

**Comment by iandol** [comment]
The things I'd like to do with metadata I think are covered by your methods. I want to read a value in one metadata key then set or replace another...

The major issues are to set multi value keys like multi-author or multiple keywords, but I think just creating a YAML string should handle these cases right?

I think this emphasizes needing to add logging metadata passed to pandoc...

**Comment by htdebeer** [comment]
What I was wondering, what would the following piece of code do:

    metadata.set("my.nice.property", "---\nkey: value\n...\n")

- if `my.nice.property` does exist, it makes sense to add or replace `key` and set `value`.
- if `my.nice` does exist, but `property` does not, should it be created or should there be a warning?

Also, last night I added the `_debug` metadata property to enable extra debugging information. I now only use it if the pandoc-type API version in the document is smaller than that used in paru, but it could be used to show more debugging information. What kind of information would you like/expect to be able to see when you set `_debug`?

**Comment by iandol** [comment]
Hm, I suppose it depends on what is being set!

If `my.nice.property` is a metalist, should the default behaviour be an error if a key is provided as this is invalid right, or you could silently drop the key and just add a value.

If `my.nice` exists but not `property`, I think it should be created. I can well imagine wanting to add a child key:value to a metalist entry:

```YAML
author:
    - John Doe
        <institute: MoD> # we want to add this key:value to the first author in the list
```
-----

Also, shouldn't it be debug_ if you want pandoc to ignore it?

**Comment by htdebeer** [comment]
You're right. The pandoc manual states clearly:

> Fields with names ending in an underscore will be ignored by pandoc. (They may be given a role by external processors.)

I have update the code accordingly. Thanks for noticing!

It'll be in the next version, but there are some more bugs I want to fix this weekend, so I'll wait with releasing after I've fixed those as well.

And I agree with you on your observations regarding the behavior of manipulating metadata.

**Comment by iandol** [comment]
> What kind of information would you like/expect to be able to see when you set _debug?

So my main existing issue is that metadata can be specified several ways: YAML or other metadata within the document, from the commandline, from filters. It is not clear to track what is finally sent to Pandoc, i.e. what is the combined final metadata? Now Paru/Pandocomatic could combine the document and commandline metadata, but you can't access metadata injected via filters (filters run outside of paru's scope). Nevertheless the document + commandline combined metadata list would still be useful information. I think for this you really need pandocomatic to handle this as it contains the final commandline for each template.

**Comment by htdebeer** [comment]
Why cannot you access metadata injected via filters? The metadata is added to the AST that is send to the filter and then output again back to pandoc. I.e. If I have two filters and I set metadata in the first filter, it will be available in the second filter, and finally also in the template. Of course, a filter does not know how the metadata got into the AST except for the metadata it sets itself.

(This would allow for an "enable_metadata.rb" filter that you could run before a filter you want to inspect more closely, which would not do anything more than set the property "debug_".)

Maybe we should make the "debug_" property not a boolean but a map in which you can set extra options like "show_metadata"? That would allow to see how the metadata changes from filter to filter.

For pandocomatic, we could also mixin the "command line" options into the metadata somewhere. Maybe in the "pandocomatic_.pandoc" property. It is already used anyway, and adding any extra information after it has been read and used to setup pandocomatic/pandoc should not matter.

**Comment by iandol** [comment]
Yes OK, the filter has access to the AST metadata of course. But I thought a filter cannot cleanly output the metadata "separate" from stdout AST? How can the filter communicate to pandocomatic?

> For pandocomatic, we could also mixin the "command line" options into the metadata somewhere. 

Yes, this is sort of what I was getting at here: https://github.com/htdebeer/pandocomatic/issues/16 — if we could set metadata explicitly, not do it via -M commandline, then pandocomatic would inject the metadata into the AST. 

I probably don't understand well enough the order of events, I naively assume that pandocomatic calls pandoc and pandoc itself runs the filters, which means each paru filter understands only what pandoc sends it and pandocomatic has no final "combined" version from which it can make a detailed summary?

**Comment by htdebeer** [comment]
Your operational understanding of pandocomatic and pandoc and filters is correct. Pandocomatic set up the pandoc command, and pandoc executes filters, and pandoc outputs the final document. After the first setup, pandocomatic has no communication with pandoc or filters anymore. That does not mean we cannot add something like that.

Actually, you can output metadata separate from STDOUT in a filter: If I am debugging a filter written in paru I always use `warn` to print to STDERR, which is ignored by pandoc.

One (bad) way to communicate between pandocomatic and paru and pandoc could be to use STDERR. Better would be to use a custom stream or a temporary log to communicate between paru filters and pandocomatic.
