### ISSUE TITLE
Selector "classes" regex is too restrictive, disallows the valid underscore character

### ISSUE THREAD

**Issue by danblaker** [htdebeer/paru#50]
The Selector class matcher uses the regular expression `\.[a-zA-Z-]+`, which prevents selectors with underscores. Technically, any character can be used in a CSS class name as long as it's escaped properly in the stylesheet rule; but the `_` character is valid without being escaped, and indeed underscores are commonly used in modern CSS namespacing conventions such as [BEM](https://en.bem.info/methodology/naming-convention/). There's an alternative regex in [this StackOverflow answer](https://stackoverflow.com/a/449000).

**Comment by htdebeer** [comment]
Thanks for submitting this bug with a suggestion to fix it! During the weekend I will implement your suggestion and update paru.

**Comment by htdebeer** [comment]
Done. You can test the fix in paru-0.3.2.3.
