### ISSUE TITLE
Pandoc V2.8 

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#51]
Hi Huub, hope you are well. This was just a small heads-up that the upcoming V2.8 of Pandoc will include a few command-line option changes:

https://github.com/jgm/pandoc/blob/master/changelog.md

There is a nice new feature to call YAML defaults, and I hope this will work alongside pandocomatic (I haven't tested anything yet though):
https://github.com/jgm/pandoc/blob/master/MANUAL.txt#L1423

**Comment by htdebeer** [comment]
Thanks for letting me know! Once pandoc v2.8 is released, I'll update paru.

**Comment by iandol** [comment]
Hi Huub, 2.8 was finally released (it took longer than I thought, but there are _lots_ of changes!):

https://github.com/jgm/pandoc/releases/tag/2.8

**Comment by htdebeer** [comment]
I saw the release notes! This weekend I am in the empty North, but when I get back, I will start update paru to reflect these changes. As far as I can see, most changes are not too much of a problem for paru, as it is just a thin wrapper. I will create a new minor version (0.4.*) to reflect the new option and deprecation of options. 

The implications for pandocomatic seem more significant. Particularly the introduction of `--defaults` and `--metadata-file`, and the change in merging metadata. This might conflict with how pandocomatic templates work at the moment. On the other hand, maybe we can build some of pandocomatic's functionality on top of these new features.

**Comment by iandol** [comment]
Hi Huub, enjoy the North!

My feeling would be to try to keep pandocomatic as is (adapted to keep working of course). `--defaults` is a great new native addition for people who don't want any other dependencies, but having a single YAML file with Pandocomatic where you can **extend:** other templates is still a really nice and elegant workflow. For my Scrivener workflows I will probably create a `--defaults` version, but will also keep pandocmatic as a more advanced option.

**Comment by htdebeer** [comment]
I've created paru 0.4.0. Some tests were broken after the update to pandoc 2.8, but updating to pandoc types version 1.20 and regenerating all test files solved those issues. 

Feedback is welcome.

**Comment by iandol** [comment]
From pandocomatic I still see this:

```
The pandoc option 'shift_heading_level_by' (with value '1') is not recognized by paru. This option is skipped.
```

I assume pandocomatic 0.2.5.5 is still using 0.3.2.4, so I'll wait for that then retest.

**Comment by htdebeer** [comment]
Yes, pandocomatic does not yet work with pandoc 2.8 / paru 0.4. I tried to run a test yesterday and discovered some issues. I will look into them later this week and also release a new version of pandocomatic.
