### ISSUE TITLE
Trouble configuring paru to pass pandoc an external metadata file

### ISSUE THREAD

**Issue by NickBarreto** [htdebeer/paru#53]
I was looking at commit ec42eb72934e2ae61ee0544c398a76bd2a552071 and how it's added support for pandoc --metadata-file, but I can't seem to get this to work with paru.

I assumed the rubyesque way of setting this option would be with an underscore instead of hyphen "metadata_file 'filename.yaml'" 

```
file = 'test.md'
Paru::Pandoc.new do
  from 'markdown-smart'
  to 'markdown-smart'
  standalone true
  output 'test-1.md'
  metadata_file 'metadata.yaml'
end.convert_file file
```

However, I get an error when I try this.

`NoMethodError: undefined method 'metadata_file' for #<Paru::Pandoc:0x00007fc55d30ec68>
did you mean?  metadata-file`

When I try and use `metadata-file` in my options instead, I get a ruby syntax error because of the hyphen. 

Is there a bug in this implementation, or am I not configuring this option correctly in my example above?

**Comment by htdebeer** [comment]
I can reproduce this issue. This seems to be a bug. I will resolve it over the weekend.

**Comment by htdebeer** [comment]
Weekend came early! I've created a fix and updated paru. Please install version 0.4.0.1 and test your scenario again.

**Comment by NickBarreto** [comment]
Yep! Paru 0.4.0.1 is working perfectly using `metadata_file 'filename.yaml'` as the option to pass in an external .yaml file.

Thanks very much!
