### ISSUE TITLE
Filter selection fails to match in certain scenarios

### ISSUE THREAD

**Issue by NickBarreto** [htdebeer/paru#54]
I'm not sure why, but in certain circumstances, a filter will fail to match an element that it should match. 

For example, given this markdown source:
```
# Chapter One

## A location

This is chapter one. It has a bunch of text.

# Chapter Two

## Another location

This is chapter two. It has some more text.

## A Subsequent location

The end.
```

The following filter will fail to match the first two H2 headings:

```
require 'paru/filter'

Paru::Filter.run do
  with 'Header' do |header|
    warn "Header is #{header.inner_markdown}"
    if header.level == 1
      header.markdown = "\\chapter\*\{#{header.inner_markdown.strip}\}\\label\{#{header.attr.id}\}"
    end
    if header.level == 2
      header.markdown = "\\section\*\{#{header.inner_markdown.strip}\}\\label\{#{header.attr.id}\}"
    end
    if header.level == 3
      header.markdown = "\\subsection\*\{#{header.inner_markdown.strip}\}\\label\{#{header.attr.id}\}"
    end
  end
end
```

I guess the manipulation of a given node's markdown is resulting in the following node being skipped over by the filter, as the nodes only seem to be passed over when they are immediately following another node that has matched. 

It's definitely related to the 'markdown' method manipulation, as if I simply run a filter like this one below, every heading node is listed:

```
Paru::Filter.run do
  with 'Header' do |header|
    warn "Header is #{header.inner_markdown}"
  end
end
```

At the moment I'm resorting to a relatively hacky check of the next node in the index's type, and if it is also a Heading I am manipulating it as well. But ideally I would expect this filter to match every heading node in the document. 

Should I be manipulating the output of those nodes in a different way? Or is there a bug that is resulting in a skipped over node in the index when a mode has been altered?

**Comment by htdebeer** [comment]
I can reproduce the issue. It might have to do with assigning a string with LaTeX code to the markdown property of the header. It is not clear what you try to accomplish with that.

Anyway, if I change your filter to:

```{ruby}
#!/usr/bin/env ruby
require 'paru/filter'

Paru::Filter.run do
  with 'Header' do |header|
    
    if header.level == 1
      header.markdown = "chapter #{header.inner_markdown.strip} + #{header.attr.id}"
    end
    
    if header.level == 2
      header.markdown = "section #{header.inner_markdown.strip} + #{header.attr.id}"
    end
    
    if header.level == 3
      header.markdown = "subsection #{header.inner_markdown.strip} + #{header.attr.id}"
    end

  end
end
```

it seems to visit all header nodes. 

Note that the `some_node#markdown(str)` method/property will convert `str` with pandoc into an AST and merge that into the AST representation of `some_node`. That is likely to give odd results if pandoc sees LaTeX code whilst expecting markdown.

If you want to change the header to LaTeX code, it is better to replace the Header nodes in the filter with a RawBlock LaTeX node. For example, something like this:

```{ruby}
#!/usr/bin/env ruby
require 'paru/filter'

def create_raw_latex_node(type, header)
    Paru::PandocFilter::RawBlock.new([
        "latex", 
        "\\#{type}chapter\*\{#{header.inner_markdown.strip}\}\\label\{#{header.attr.id}\}"
    ])
end

Paru::Filter.run do
  with 'Header' do |header|


    if header.level == 1
        header.parent.replace(header, create_raw_latex_node("chapter", header))
    end
    
    if header.level == 2
        header.parent.replace(header, create_raw_latex_node("section", header))
    end
    
    if header.level == 3
        header.parent.replace(header, create_raw_latex_node("subsection", header))
    end
    
  end
end
```

But I do not know if you had that in mind.

**Comment by NickBarreto** [comment]
Hi Huub,

Thank you very much for having a look.

Fine-tuning the LaTeX output is exactly what I'm after here. By default pandoc produces numbered chapter and section elements, and I'm adding the star '*' to make them un-numbered, for example. 

Creating a raw node is essentially what I'm doing in a roundabout way. Having a method to do so seems like a good idea and will make the filter a bit more declarative.

I really like this approach and will likely implement it in a few other filters too. I'll do some testing and see if it does away with the issue.
 
I have a few questions though: if I create a raw node in this way, will the inner_markdown of the heading be parsed as markdown? Or will I get a raw output? For example, if a heading has an italicized word, will I see it wrapped in '*' in that raw block? Would I need to parse the inner_markdown into latex first, and then add it to the rawblock?

**Comment by NickBarreto** [comment]
OK, yes, it does seem like the raw markdown gets passed into the new node. So I added another method: 

```ruby
require 'paru/filter'
require 'paru/pandoc'

def latex_convert(string)
  Paru::Pandoc.new do
    from 'markdown'
    to 'latex'
  end << string
end

def create_raw_latex_node(type, header)
  Paru::PandocFilter::RawBlock.new([
    'latex',
    "\\#{type}\*\{#{latex_convert(header.inner_markdown.strip)}\}\\label\{#{header.attr.id}\}"
  ])
end

Paru::Filter.run do
  with 'Header' do |header|
    # Change the output so chapters and sections aren't numbered
    header.parent.replace(header, create_raw_latex_node('chapter', header)) if header.level == 1
    header.parent.replace(header, create_raw_latex_node('section', header)) if header.level == 2
    header.parent.replace(header, create_raw_latex_node('subsection', header)) if header.level == 3
  end
end
```

I think this approach of running smaller paru/pandoc conversions may address some other implementation issues I've been having with some other filters, too. All of which is to say this issue is definitely sorted, but I'll come back if that's okay if I have further questions or doubts.

Thanks again, Huub. Paru is a great library to work with. Hopefully as I get more and more familiar with it I can help and contribute and give something back.

**Comment by htdebeer** [comment]
Now that I understand your use-case, it makes more sense!  You might have a look at [custom wreiters](https://pandoc.org/MANUAL.html#custom-writers), although that might be way more work that the solution you now have.

At the moment, Paru's `Node`s only support getting/setting Pandoc's markdown via a convenience method. Of course, you can change the whole AST of a node by creating, removing, editing, moving sub nodes. For small changes that is okay, but for larger pieces of document this is a hassle. That is why I added the convenience markdown methods.

I would welcome a pull request for convenience methods for LaTeX or HTML or whatever. Have a look at [`node.rb`](https://github.com/htdebeer/paru/blob/f31a6b1ec7b8b17687deee45324b691025df6b31/lib/paru/filter/node.rb#L340-L400) how I did this for markdown.
