### ISSUE TITLE
Using pandoc within a filter is confusing smart conversion of quotes

### ISSUE THREAD

**Issue by NickBarreto** [htdebeer/paru#55]
Using the pattern suggested in #54, I have setup a filter to be able to inject an HTML class to a blockquote element in HTML.

filter.rb:
```ruby
require 'paru/filter'
require 'paru/pandoc'

def html_convert(string)
  Paru::Pandoc.new do
    from 'markdown'
    to 'html'
  end << string
end

def classed_blockquote(blockquote_class, contents)
  Paru::PandocFilter::RawBlock.new([
    'html',
    "<blockquote class='#{blockquote_class}'>\n#{html_convert(contents)}</blockquote>"
  ])
end

Paru::Filter.run do
  with 'Div.classed_blockquote' do |div|
    content = div.inner_markdown
    blockquote_class = div.attr['blockquote_class']
    div.parent.replace(div, classed_blockquote(blockquote_class, content))
  end
end
```

The intention here, as an example, would be to apply a class which is related to CSS presentation of poetry. Given the following markdown:

test.md
```
:::{.classed_blockquote blockquote_class='hanging_indent'}

‘Let 'em talk 'bout what they think they see

Let ’em talk 'bout how they see us be

'Cause baby, we got nothin' to prove

We earned our scars and put in our time
:::
```

I expect this output:

```html
<blockquote class='hanging_indent'>
<p>‘Let ’em talk ’bout what they think they see</p>
<p>Let ’em talk ’bout how they see us be</p>
<p>‘Cause baby, we got nothin’ to prove</p>
<p>We earned our scars and put in our time</p>\n</blockquote>
 ```

However, I think related to my use of `inner_markdown` to access the node's children, the result I'm getting turns the initial quote mark the other way around, no matter what I do, even if I escape it as `"\‘"`: 

```html
<blockquote class='hanging_indent'>
<p>’Let ’em talk ’bout what they think they see</p>
<p>Let ’em talk ’bout how they see us be</p>
<p>‘Cause baby, we got nothin’ to prove</p>
<p>We earned our scars and put in our time</p>\n</blockquote>
 ```

I've tried a few ways of individually parsing the nodes along the lines of the below snippet, as I thought perhaps due to the nesting I was confusing pandoc, but still suffer from the same issue.

```ruby
children = div.children
children.each do |node|
  html_convert(node.inner_markdown)
end
```
 
Anytime I attempt to convert a node to html from within a filter, I'm seeing results in the quote mark being turned the wrong way around. This doesn't happen if I simply run the markdown above without the filter (though of course the output paragraphs are wrapped in `<div class="classed_blockquote" data-blockquote_class="hanging_indent">` instead. 

I'm obviously approaching this in a way that is confusing pandoc's implementation of --smart, likely due to the nesting of elements or the use of 'inner_markdown', but I'm not sure how else to access a node's contents.

Should I be individually converting them to_ast/json and then transforming that into my result HTML?

**Comment by htdebeer** [comment]
This is an odd one! I can reproduce the issue. As you suspect, this might have something to do with Pandoc's "smart" extension. It is enabled by default for the "markdown" format. To me, this does not make sense for the `inner_markdown` and `markdown` methods on `Node` because they are about manipulating the AST in plain text, not nicely formatted text.

I can update paru by using `markdown-smart` as the output format for the `markdown()` method and `markdown+smart` for the `markdown=()` method. As far as I can see, this seems to solve your issue. I cannot oversee if this change will have much impact on the use of the `markdown` methods otherwise, but as a user I expect the markdown I process and update in my filters to not do anything "smart" with my quotes. So this might be an improvement overall.

Can you test your situation with paru version 0.4.0.2?

**Comment by NickBarreto** [comment]
Upgrading to paru 0.4.0.2 certainly seems to address the issue in the test files I'd built, and in a few sample tests more widely.

I agree with you that this change makes sense. When you set the target and source formats in your Paru::Pandoc instance, you can be selective about whether you want --smart on or not, and that does seem to take care of any educating quotes where necessary. To have internal filter methods also using --smart is maybe doing the work more than once which perhaps is what was causing the issue in the first place.
