### ISSUE TITLE
undefined method empty - metadata.rb:49

### ISSUE THREAD

**Issue by edusantana** [htdebeer/paru#59]
Hi, [I'm getting this error](https://travis-ci.org/github/abntex/limarka/jobs/707785654):

```
Erro: JSON parse error: Error in $: Incompatible API versions: encoded with [1,20] but attempted to decode with [1,21].
/var/lib/gems/2.7.0/gems/paru-0.4.0.1/lib/paru/filter/metadata.rb:49:in `initialize': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /var/lib/gems/2.7.0/gems/paru-0.4.0.1/lib/paru/filter.rb:272:in `new'
	from /var/lib/gems/2.7.0/gems/paru-0.4.0.1/lib/paru/filter.rb:272:in `filter'
	from /var/lib/gems/2.7.0/gems/paru-0.4.0.1/lib/paru/filter.rb:244:in `run'
	from ./filtro.rb:6:in `<main>'
Error running filter filtro.rb:
Filter returned error status 1
```

Can you help me?

**Comment by iandol** [comment]
@edusantana -- you need to update your Paru to V0.4.1 as this is the version that supports the latest Pandoc V2.10...

https://github.com/htdebeer/paru/releases/tag/0.4.1

**Comment by edusantana** [comment]
Thanks!

**Comment by htdebeer** [comment]
@edusantana Thanks for your question! I have added it to the FAQ and made a note at the start of the README. And, as always, thanks to @iandol for helping out!
