### ISSUE TITLE
Pandoc V2.11

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#60]
Hi Huub,

There are a few significant changes coming for Pandoc V2.11, the biggest being a removal of pandoc-citeproc as a seperate binary, it is now integrated directly: 

https://github.com/jgm/pandoc/commit/e0984a43a99231e72c02a0a716c8d0315de9abdf

Changes for pandoc-types: https://github.com/jgm/pandoc-types/blob/master/changelog 

Best, Ian

**Comment by iandol** [comment]
Nightlies are succesfully building for V2.11 here: https://github.com/jgm/pandoc/actions?query=workflow%3ANightly

**Comment by iandol** [comment]
Changelog here: https://github.com/jgm/pandoc/blob/master/changelog.md — the date of release is supposedly today...

**Comment by iandol** [comment]
…and released: https://github.com/jgm/pandoc/releases/tag/2.11

**Comment by htdebeer** [comment]
Released 0.4.2 with compatibility with pandoc 2.11. The test set seems to run now, but the table related types seem to be represented differently from other types. Maybe this means that the rest of the types will also get a similar overhaul. If so, paru needs to be rewritten. But that's for another time.

**Comment by iandol** [comment]
Thanks as always Huub! Does pandocomatic need updating for the command-line changes?

**Comment by htdebeer** [comment]
I need to update the pandocomatic tests anyway because of the changes to the default CSS in the HTML template. I'll create an issue for it and then look into this over the weekend.
