### ISSUE TITLE
A regression with old versions of Psych

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#64]
The fix for #63 has a side effect for people using an old version of psych:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/psych.rb:271:in `load': unknown keyword: permitted_classes (ArgumentError)
```

Checking older docs, indeed `load` does not have the permitted_classes property, only `safe_load` does. Therefore the fix:

```ruby
contents = YAML.load yaml_string, permitted_classes: [Date]
```

fails for old versions of psych 😭 — this bit someone here: https://github.com/iandol/scrivomatic/issues/45 — the solution is fairly easy to update the gem to a new version. But I want to raise this in case you would prefer to implement a solution in paru to work around this compatibility issue?

Using `safe_load` explicitly would solve this (as I understand it, `load` method used to be an alias to `unsafe_load` then the alias was switched to `safe_load`, so that method is present in older psych) — for the newer psych these are therefore identical, but for the older psych `safe_load` is more restrictive than `load`. Another alternative is to somehow switch the code based on the psych library version?

**Comment by htdebeer** [comment]
Switching to "safe_load" isn't a problem, assuming Psych isn't breaking or deprecating that method next.

**Comment by iandol** [comment]
As I understand it `load` is an alias for `safe_load`:

https://github.com/ruby/psych/blob/master/lib/psych.rb#L369

So I suspect that `safe_load` is unlikely to be removed...
