### ISSUE TITLE
Compatibility with Ruby V2.6.8 that is default with macOS

### ISSUE THREAD

**Issue by iandol** [htdebeer/paru#72]
Hi Huub,

It seems that since V1.0.0 of paru, compatibility with the system ruby that comes as standard with macOS has been lost:

```
▷ sudo gem install paru:1.0.0
Fetching paru-1.0.0.gem
ERROR:  Error installing paru:
	There are no versions of paru (= 1.0.0) compatible with your Ruby & RubyGems
	paru requires Ruby version >= 2.7.6. The current ruby version is 2.6.8.205.
```

I was wondering if there was some way to maintain compatibility with the system ruby as several users on macOS do benefit from not having to manually install their own updated ruby if possible...

**Comment by htdebeer** [comment]
Yes and no. I don't mind lowering the required ruby version in the gem file. I mainly follow the Ruby release cycle, but I expect that paru still works on fairly old ruby versions.

However, I won't look into issues caused by EOL Ruby versions. And if useful, I will use newer Ruby features without regard for EOL Ruby versions.

So, next release, I'll try to lower the required ruby version. What version do you want that to be?

**Comment by iandol** [comment]
Hi Huub, I understand this requirement is annoying. Currently the system ruby that comes by default with macOS is:

```
▶︎ ruby -v
ruby 2.6.8p205 (2021-07-07 revision 67951) [universal.x86_64-darwin21]
```

I hope that the changes between V2.6.8 and V2.7.x shouldn't cause too much trouble: https://www.ruby-lang.org/en/news/2019/12/25/ruby-2-7-0-released/

Note: Apple may remove Ruby at some point, they already did this with Python V2.x. If so then the problem will be removed, and users can install the latest Ruby...

**Comment by htdebeer** [comment]
I've published paru verison 1.0.3 with the downgraded ruby requirements. Can you test if it runs on a mac OSX system with the outdated version of ruby?

**Comment by iandol** [comment]
Yes, I ran a bunch of my filters with Ruby V2.6.8 and paru V1.0.3 and everything ran without error. I don't use the other features of paru so it is harder for me to test that. If you didn't see any regressions elsewhere then this can be closed.

**Comment by htdebeer** [comment]
All right! Thanks for testing.
