### ISSUE TITLE
Convert footnotes to sidenotes

### ISSUE THREAD

**Issue by sudeeptarlekar** [htdebeer/paru#74]
Thanks for this wonderful gem.

I am still exploring this, so apologies if this is irrelevant question. When we convert markdown to html, pandoc adds the footnote. Is there any way I can add sidenotes instead of footnotes?

I explored other solutions which passes custom filter `pandoc-sidenote`, just curious is there any way to use that along with my custom filters?

Thanks in advance,

**Comment by htdebeer** [comment]
You can use as many filters as you want, like so:

```
pandoc --from markdown --to html --filter yourfilter --filter pandoc-sidenote --filter anotherfilter input.md
```

As for the footnotes in HTML, you can also try to make them sidenotes with CSS. You can include custom CSS in your pandoc generated HTML pages, or even supply your own base HTML template for pandoc to use. You read more about this in pandoc's manual.

**Comment by sudeeptarlekar** [comment]
Yes, but this is from command line, I am looking for ways to convert from Rails console.

**Comment by htdebeer** [comment]
On August 4, 2022 12:49:33 PM GMT+02:00, Sudeep Tarlekar ***@***.***> wrote:
>Yes, but this is from command line, I am looking for ways to convert from Rails console.
>

Paru is a wrapper around pandoc and offers the same functionality. In a pandoc converter, you can use the filter method multiple times to configure to use multiple filters with pandoc.

On Sunday evening, when I'm back from holiday, I can show an example of this, if you need it.
Huub de Beer
***@***.***
https://heerdebeer.org

**Comment by sudeeptarlekar** [comment]
Hey, thanks for taking time out on you holiday. It was silly mistake from my side, missed quotes `'pandoc-sidenote'` around filter declaration.
Got it working, adding code snippet here for future reference

```
require 'paru/pandoc'
require 'paru/filter'

converter = Paru::Pandoc.new do
  from "markdown+tex_math_single_backslash"
  to "html5+smart"
  filter "pandoc-sidenote"
  css "./pandoc.css"
  css "./skylighting-solarized-theme.css"
end

file = File.open("./index.md")

converter.convert file.read
```
