### ISSUE TITLE
Provide a way to customize `MARKDOWN2JSON`

### ISSUE THREAD

**Issue by UlyssesZh** [htdebeer/paru#79]
For example, to make the tab characters being preserved when using `Paru::PandocFilter::Node#markdown=`, I have to
```ruby
Paru::PandocFilter::MARKDOWN2JSON.__send__ :preserve_tabs
```
This is kind of a hack. What is the correct way to do this?

**Comment by UlyssesZh** [comment]
In my blog, I use tabs in code blocks and use `tab-size` in CSS to conveniently change tab size without needing to touch the source files of the articles.

I also wrote a Pandoc filter to transform a code block into some HTML. Whether I use HTML tags directly in Markdown or use raw blocks, the tabs will be converted to 4 spaces. I have to turn on `--preserve-tabs`.

**Comment by htdebeer** [comment]
Starting in version 1.2, paru preserves tabs by default. Please test this version to see if it works for your use case.

(Note. I also upgraded the minumum Ruby version to 3.0.6)
