### ISSUE TITLE
metadata.delete does report error?

### ISSUE THREAD

**Issue by kusmi** [htdebeer/paru#8]
In previous version I could delete metadata entries by typing:

`metadata.delete("date”)`

as of version paru-0.2.4.6 it does not work anymore and I get:

/var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/meta_map.rb:185:in

>  `select': undefined method `has_key?' for []:Array (NoMethodError)
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/meta_map.rb:139:in `has?'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/meta_map.rb:150:in `delete'
> 	from bin/removeMetadataFilter.rb:6:in `block in <main>'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter.rb:268:in `instance_eval'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter.rb:268:in `block in filter'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/ast_manipulation.rb:101:in `each_depth_first'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/ast_manipulation.rb:102:in `block in each_depth_first'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/node.rb:104:in `block in each'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/node.rb:103:in `each'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/node.rb:103:in `each'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/ast_manipulation.rb:102:in `each_depth_first'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter.rb:266:in `filter'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter.rb:228:in `run'
> 	from bin/removeMetadataFilter.rb:4:in `<main>’

Of course I’m not 100% sure if this is a correct way of removing metadata (I have metadata in latex/pdf output but remove them for HTML output)

I have attached a test example - you can execute:
`pandoc "test.markdown" --filter testFilter.rb -o test.html`

[Metadata_Remove.zip](https://github.com/htdebeer/paru/files/1047087/Metadata_Remove.zip)

**Comment by htdebeer** [comment]
Thanks for your bug report!

I can reproduce the issue. It looks like paru has trouble with the `%`-based metadata somehow.

 I'll investigate further and create a fix this weekend.

**Comment by htdebeer** [comment]
Actually, that is not true. Upon further investigation it appears that paru gets into trouble after removing all the keys from the metadata.

I've created a fix. It'll be part of the next release of paru. You can download version 0.2.4.9 from the releases directory if you want to test it. I plan to fix some more bugs this weekend. After I do so, I'll release this new version to rubygems as well.
