### ISSUE TITLE
Add Gemfile.lock and remove releases

### ISSUE THREAD

**Issue by UlyssesZh** [htdebeer/paru#87]
Remove the releases dir from the repo because it is not meant to be in a repo for source control. The main reason is that it is a waste of space and bandwidth (for the hosting platform and for people downloading the source) since those files can be generated reproduceably with a simple rake task (ideally). Although removing the files now doesn't really save the space for people cloning the repo (except if using `--depth 1`), it will save space for people downloading the source as a tarball or zip. It will also save space in the future if you would include more files in the releases dir in the future otherwise.

Add Gemfile.lock to the repo for reproduceability concerns. Generally a lockfile should always be included in a source control repo.

**Comment by htdebeer** [comment]
A lockfile is a good idea! Will add.

As for the releases directory, I agree that keeping most old releases isn't needed. At the same time I'd like to keep some of the last releases. All files in the repo, including the releases, are available as static files on my website. I will look into this further.

**Comment by UlyssesZh** [comment]
You can include the links in GitHub releases instead, such as https://github.com/htdebeer/paru/releases/download/1.4.0/paru-1.4.0.gem.

**Comment by UlyssesZh** [comment]
Only removing old releases but keeping adding new releases is still bad because they will continue to exist in git history.

**Comment by UlyssesZh** [comment]
The documentation dir should also be deleted for similar reasons.

If you still want to have a repo containing documentation, you can create a branch called "doc" and use GitHub actions to automatically generate documentation and push them there whenever your master branch gets pushed. Similarly, you can create a branch called "releases" and let GitHub actions to build and push a new gem there whenever you publish a new release.

**Comment by htdebeer** [comment]
The documentation directory contains the source markdown files for the manual. This directory isn't automatically generated. I want to keep these documentation files in the repository alongside paru's source code.

Paru's API documention is automatically generated, but that output hasn't been in the repository for years :-)

**Comment by UlyssesZh** [comment]
I see that now. Sorry I didn't look carefully.

**Comment by htdebeer** [comment]
I've removed the `releases` directory and updated the manual to reflect how to build and install paru gem locally. Also added `Gemfile.lock`.
