### ISSUE TITLE
Replacing outer_markdown does not always work (e.g. replacing with embedded LaTeX)

### ISSUE THREAD

**Issue by kusmi** [htdebeer/paru#9]
When replacing elements outer_markdown:

- it sometimes work (see attached sample code) e.g. when I try to replace an image-object with `**Bold Text`

- sometimes it does not completely work, e.g. when I try to replace it with `# Chapter`, then the resulting file will omit the `#` and will just include the word “Chapter”.

- When I try to replace it with embedded LaTeX command, it reports an error:

> 
> /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/node.rb:103:in `each': undefined method `each' for nil:NilClass (NoMethodError)
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/markdown.rb:87:in `outer_markdown='
> 	from testFilter.rb:10:in `block (2 levels) in <main>'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter.rb:289:in `with'
> 	from testFilter.rb:7:in `block in <main>'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter.rb:268:in `instance_eval'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter.rb:268:in `block in filter'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/ast_manipulation.rb:101:in `each_depth_first'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/ast_manipulation.rb:102:in `block in each_depth_first'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/node.rb:104:in `block in each'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/node.rb:103:in `each'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/node.rb:103:in `each'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/ast_manipulation.rb:102:in `each_depth_first'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/ast_manipulation.rb:102:in `block in each_depth_first'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/node.rb:104:in `block in each'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/node.rb:103:in `each'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/node.rb:103:in `each'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter/ast_manipulation.rb:102:in `each_depth_first'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter.rb:266:in `filter'
> 	from /var/lib/gems/2.3.0/gems/paru-0.2.4.8/lib/paru/filter.rb:228:in `run'
> 	from testFilter.rb:6:in `<main>'
> pandoc: Error running filter testFilter.rb
> 

You can run the example code with:
`pandoc "test.markdown" --filter testFilter.rb -o output.markdown`

Again I’m not 100% how to write a replacing filter. I also tried to replace it with an Paru-Object (e.g. RawBlock or RawInline - but it did not work either)

[Replace_with_Markdown.zip](https://github.com/htdebeer/paru/files/1047159/Replace_with_Markdown.zip)

**Comment by htdebeer** [comment]
I'll look into this issue over the weekend.

With the `inner_markdown` and `outer_markdown` there are some unclear cases:
- what should happen if I try to replace the contents of a inline element with the contents of a block contents and vice versa?
- what should happen if I try to replace an inline element by a block element?

(Replacing a block element by an inline element always works as I can wrap the inline element in a block element like Para or Plain).

**Comment by htdebeer** [comment]
To replace an image, which is an Inline level node, with a header, which is a block level node, replace the image's parent instead:

```
#!/usr/bin/env ruby
require "paru/filter"

Paru::Filter.run do
    with "Image" do |i|
        i.parent.markdown = "# Chapter"
    end
end
```

Replacing inline level nodes in place with block level nodes results in an unsound document that pandoc does not understand anymore.

**Comment by htdebeer** [comment]
Idem for your example with the RawBlock containing LaTeX code.

In short:

- replace block level nodes with block level nodes
- replace inline level nodes with inline level nodes
- an inline node does have a parent, so you can always replace an inline node's parent by a block level node.

Do note that for version 0.2.5 of paru, I am depricating `outer_markdown`. Instead, each node will have a `markdown` method and some nodes will have an `inner_markdown` method.
